version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: bigbluebutton:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: v2            # Required. Target branch
    upstream: bigbluebutton:v2    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: v2.6-alpha
    upstream: bigbluebutton:v2.6-alpha
    mergeMethod: hardreset
    mergeUnstable: false
  - base: v3.0-alpha
    upstream: bigbluebutton:v3.0-alpha
    mergeMethod: hardreset
    mergeUnstable: false
#label: ":arrow_heading_down: Pull"  # Optional